# create a config for connecting to prometheus to grafana

apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-server:9090
  isDefault: true
  jsonData:
    timeInterval: "5s"
    httpMethod: GET
  version: 1
  editable: true
  
