# compose file to run prometheus and grafana containers using a sinlge network and volume
# to allow them to communicate and share data
version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - prometheus-net

networks:
  prometheus-net:

volumes:
  prometheus_data:
  grafana_data:


